create table MAGAZINE_STAND.MAGAZINES (
	ID 				bigint generated by default as identity,
	TITLE 			varchar(255) not null,
	PRICE 			numeric(19, 2),
	DATE_OF_ISSUE 	date,
	FILE_LOCATION 	varchar(255),
    primary key (ID)
);