--create schema if not exists MAGAZINE_STAND;

create table if not exists MAGAZINES (
	ID 				bigint generated by default as identity,
	TITLE 			varchar(255) not null,
	PRICE 			numeric(19, 2),
	DATE_OF_ISSUE 	date,
	FILE_LOCATION 	varchar(255),
    primary key (ID)
);

insert into MAGAZINES (TITLE, PRICE, DATE_OF_ISSUE, FILE_LOCATION)
		values	('National Geographic', 12, '2021-11-15', '/magazines/National-Geographic-2021-11-15.pdf'),
				('People Magazine', 11, '2021-12-31', '/magazines/People-2021-12-31.pdf'),
				('TIME Magazine', 5, '2021-11-08', '/magazines/TIME-2021-11-08.pdf'),
				('Cosmopolitan', 9.5, '2021-12-01', '/magazines/Cosmopolitan-2021-12-01.pdf'),
				('The New Yorker', 8.99, '2022-01-03', '/magazines/The-New-Yorker-2022-01-03.pdf');